API_ID: 18986903
API_HASH: 7457a2dd85fa14088d0bc7291143b617
BOT_TOKEN: 5609741470:AAGRjaM4kAY7hnGClI0lmR4f6yfYZuU-ceU


MONGO_URL: 'mongodb+srv://cluster0.sdxhyrl.mongodb.net/Cluster0'
REDIS_URI: 'redis-14186.c1.ap-southeast-1-1.ec2.cloud.redislabs.com'
REDIS_PORT: 14186
REDIS_PASS: bNwl9Ux9t8vzQV9Gm3yCAO2Sg77ML7A4

SESSION_API_ID: 18986903
SESSION_API_HASH: 7457a2dd85fa14088d0bc7291143b617
SESSION_STRING: 1BVtsOHwBu6Mgv6aWBmODZrM43GvUr9JxsVm-2cP6DNqwouPtquX0okevYtLtKO-Odrc_zno4AGlcaxkTTbbrZ_hd8xWKHJjcCOiVKeF5kJbWx7ZLQL24ubGEX6fl4yIvB73JzTHzyuoidi9Z42ytBu1cNQ2w44hqx2fxxgGJgzPG9utDzDy93jzxIVQaiYJ9aMMIQNqIhBmngSnbp8W0hbYH16abXbCgmDHhcVypVM0-I7y1wZ2XCS-5J9yFGlDVrl1zJ7N097A95jEog9Yt2RDZLkyJgdx6wyvppK60fNaNUDH77ILY_iO9oq75a54MBTE9GrpvNbtbGkuE7uiWFTF_b3yY01k=

ADMINS: 
  - 2035446281

OWNER: 2035446281

BOT_PIC: https://telegra.ph/file/9cf7617c98da151abbb8f.jpg
OWNER_PIC: https://telegra.ph/file/9cf7617c98da151abbb8f.jpg


SUPPORT_CHAT: logschat_group
# LOG_CHAT: 
LOG_CHAT: 



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

